### ISSUE TITLE
Gas injection valve definitions

### ISSUE THREAD

**Issue by samueljackson92** [ukaea/fair-mast-ingestion#66]
Currently we have the following definitions for the gas puffing valves _targets_ from MAST. 

```yaml
      valve_voltage:
        imas: "gas_injection.valve[:].voltage.data"
        source: 
          - name: "XDC/GAS"
            shot_range:
              shot_min: 28356
              shot_max: 30471
            channels:
              - "XDC/GAS/T/G1"
              - "XDC/GAS/T/G2"
              - "XDC/GAS/T/G3"
              - "XDC/GAS/T/G4"
              - "XDC/GAS/T/G5"
              - "XDC/GAS/T/G6"
              - "XDC/GAS/T/G7"
              - "XDC/GAS/T/G8"
              - "XDC/GAS/T/G9"
              - "XDC/GAS/T/G10"
              - "XDC/GAS/T/G11"
              - "XDC/GAS/T/G12"

          - name: "XDC/GAS"
            shot_range:
              shot_min: 1
              shot_max: 28355
            channels:
              - "XDC_GAS_T_G1"
              - "XDC_GAS_T_G2"
              - "XDC_GAS_T_G3"
              - "XDC_GAS_T_G4"
              - "XDC_GAS_T_G5"
              - "XDC_GAS_T_G6"
              - "XDC_GAS_T_G7"
              - "XDC_GAS_T_G8"
              - "XDC_GAS_T_G9"
              - "XDC_GAS_T_G10"
              - "XDC_GAS_T_G11"
              - "XDC_GAS_T_G12"

        dimensions:
          valve_channel:
          time: 
            imas: "gas_injection.valve[:].voltage.time"
```

However, for the floating point valves injected, they have the following names:

![Image](https://github.com/user-attachments/assets/0390d63d-4177-4b40-b824-7ec234c3c2f3)

It is not clear what the mappings between names and channel number would be.
